title: BYTES
description: Official website of "Brillian, Young, and Technology-Empowered Students," an accredited organization in FEU High School.
preview:
categories:
  - Project
  - Blog
  - Announcement
feu: https://www.feuhighschool.edu.ph/
facebook: https://www.facebook.com/feuhs.bytes/
instagram: https://www.instagram.com/feuhs.bytes/
thissite: https://www.bytes-feuhs.github.io/
discord: https://discord.com/invite/hrnyrY4G8b
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
show_downloads: false
google_analytics:
background: "/assets/css/home.css?v="
