title: BYTES
description: Official website of "Brillian, Young, and Technology-Empowered Students," an accredited organization in FEU High School.
preview:
categories:
  - Project
  - Blog
  - Announcement
facebook: https://www.facebook.com/profile.php?id=61563526641970
instagram: https://www.instagram.com/feuhs.bytes_official/
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
show_downloads: false
google_analytics:
background: "/assets/css/home.css?v="
